/* ===== Jood ALabbas Store — Translations ===== */
/* Edit here to update Arabic / English / Kurdish text */

/* ==================== TRANSLATIONS ==================== */
const L = {
  ar:{
    dir:'rtl',
    hTitle:'متجر جود العباس',hSub:'Jood ALabbas Store',
    welcome:'أهلاً بكم في متجر جود العباس! تسوق سعيد 🌟',
    promo:'خصم 50% — ينتهي العرض خلال:',
    search:'ابحث بالـ ID أو القياس...',rst:'مسح',
    fltBtn:'الفلاتر',applyFlt:'عرض النتائج',resetFlt:'مسح الفلاتر',
    seaLbl:'الموسم',typLbl:'النوع',sortLbl:'ترتيب حسب',
    all:'الكل',sum:'☀️ صيفي',win:'❄️ شتوي',spr:'🌸 بهاري',out:'👗 طلعة',hom:'🏠 منزلي',
    sortDef:'الافتراضي',sortAsc:'السعر ↑',sortDesc:'السعر ↓',
    res:'نتيجة',dinar:'دينار',sizes:'القياسات',
    discount:'خصم 50%',lastSize:'⚠️ آخر قياس',share:'مشاركة',
    saved:'وفّرت',copyId:'تم نسخ الرقم',
    cartT:'السلة',wishT:'المفضلة',contactT:'تواصل معنا',
    checkout:'إتمام الشراء',clearCart:'إفراغ السلة',shareCart:'مشاركة السلة',
    cartEmpty:'السلة فارغة 🛒',
    sub:'المجموع الأصلي',ship:'تكلفة النقل',tot:'المجموع النهائي',subDisc:'بعد الخصم 50%',
    ckTitle:'معلومات الزبون',namePh:'الاسم الكامل',phonePh:'رقم الهاتف',addrPh:'العنوان...',
    wa:'واتساب',tg:'تليجرام',orderNote:'يجب إرسال الرسالة لتثبيت الطلب',
    cancel:'إلغاء',back:'← رجوع',tapSizeToAdd:'اضغط على القياس للإضافة',addCart:'أضف للسلة',navInstall:'تثبيت',swipeHint:'اسحب يميناً لحذف المنتج',appInstalled:'تم تثبيت التطبيق',alreadyInstalled:'التطبيق مثبت بالفعل!',androidInstallDesc:'اضغط الزر لتثبيت المتجر على شاشتك الرئيسية.',installNow:'تثبيت الآن',iosStep1:'افتح المتجر في Safari',iosStep2:'اضغط زر المشاركة ↑ أسفل الشاشة',iosStep3:'اختر إضافة إلى الشاشة الرئيسية',iosStep4:'اضغط إضافة — تم!',desktopStep1:'افتح قائمة المتصفح ⋮',desktopStep2:'ابحث عن تثبيت التطبيق',desktopStep3:'اضغط تثبيت — تم!',szTitle:'اختر القياس المطلوب',
    loading:'جاري التحميل...',noRes:'لا توجد نتائج 😕',
    errMsg:'تعذّر تحميل المنتجات',retry:'إعادة المحاولة',
    cartAdded:'تمت الإضافة للسلة 🛒',already:'المنتج موجود في السلة',
    delQ:'هل تريد حذف هذا المنتج من السلة؟',clrQ:'هل تريد إفراغ السلة بالكامل؟',
    yes:'نعم',no:'إلغاء',
    sentQ:'هل تم إرسال رسالة الطلب بنجاح؟',sentY:'نعم، تم الإرسال',sentN:'لم يتم الإرسال',
    clrAfQ:'هل تريد تفريغ السلة الآن؟',clrAY:'نعم، أفرغها',clrAN:'لا، أبقِها',
    footer:'© 2025 متجر جود العباس — جميع الحقوق محفوظة',
    navHome:'رئيسية',navSearch:'بحث',navCart:'سلتي',navWish:'مفضلة',navContact:'تواصل',
    fpTitle:'📏 شرح القياسات',fpClose:'إغلاق',
    pwaTxt:'📲 ثبّت التطبيق على هاتفك!',pwaInst:'تثبيت',pwaSkip:'لاحقاً',
    offline:'بيانات محفوظة — تحقق من الاتصال',ptrTxt:'اسحب للتحديث',
    s55:'0-2 شهر',s60:'2-4 أشهر',s65:'4-6 أشهر',s70:'6-8 أشهر',s75:'8-10 أشهر',
    s80:'1 سنة',s90:'2 سنة',s100:'3 سنوات',s110:'4 سنوات',s120:'4-5 سنوات',
    s130:'6-7 سنوات',s140:'8-9 سنوات',s150:'10-11 سنة',s160:'12-13 سنة',s170:'14-15 سنة',
    tut:[
'📏 شرح القياسات\nاضغط على زر المسطرة الأحمر 📐 في أسفل يمين الشاشة لفتح جدول القياسات ومعرفة المقاس الصحيح لعمر طفلك.',
'🔍 البحث عن منتج\nاكتب رقم المنتج (ID) أو رقم القياس في مربع البحث. يمكنك أيضاً الضغط مباشرةً على رقم # أي منتج لنسخه.',
'⚙️ الفلاتر\nاضغط زر "الفلاتر" لتصفية المنتجات حسب الموسم (صيفي / شتوي / بهاري) أو النوع (طلعة / منزلي) أو ترتيبها حسب السعر. الرقم على الزر يُظهر عدد الفلاتر النشطة.',
'🛒 إضافة منتج للسلة\nكل منتج يُعرض قياساته كأزرار ملونة مباشرةً. اضغط على القياس المطلوب لإضافته للسلة فوراً بضغطة واحدة — بدون خطوات إضافية!',
'🛍️ السلة والدفع\nاضغط زر السلة 🛒 في الشريط السفلي لمراجعة طلبك.\n• اسحب أي منتج يميناً لحذفه\n• اضغط "إتمام الشراء"، أدخل اسمك ورقمك وعنوانك، ثم اضغط تأكيد الطلب.',
'📞 التواصل\nللتواصل وعرض شبكات التواصل الاجتماعي اضغط على "تواصل" في الشريط اسفل الشاشة .',
'🌙 الإعدادات\n• غيّر اللغة (عربي / English / کوردی) من أزرار اللغة في الهيدر\n• فعّل الوضع الداكن 🌙 من الزر بجانب اللغة\n• اسحب الصفحة للأسفل لتحديث المنتجات\n• يمكن تثبيت المتجر كتطبيق على هاتفك!'
    ],
    copyBtn:'نسخ نص الطلب',savingOrder:'جاري تسجيل طلبك...',savingSub:'لحظة من فضلك، لا تغلق الصفحة',confirmOrder:'تأكيد الطلب',orderNoteNew:'سيتم تسجيل طلبك وسنتواصل معك قريباً',orderSuccess:'تم تسجيل طلبك بنجاح! سنتواصل معك قريباً 🎉',orderSuccessOk:'حسناً',orderFail:'تعذّر تسجيل الطلب، حاول مرة أخرى',tryAgain:'إعادة المحاولة'
  },
  en:{
    dir:'ltr',
    hTitle:'Jood ALabbas Store',hSub:'متجر جود العباس',
    welcome:'Welcome to Jood ALabbas Store! Happy shopping 🌟',
    promo:'50% OFF — Offer ends in:',
    search:'Search by ID or size...',rst:'Clear',
    fltBtn:'Filters',applyFlt:'Show Results',resetFlt:'Clear Filters',
    seaLbl:'Season',typLbl:'Type',sortLbl:'Sort by',
    all:'All',sum:'☀️ Summer',win:'❄️ Winter',spr:'🌸 Spring',out:'👗 Outdoor',hom:'🏠 Home',
    sortDef:'Default',sortAsc:'Price ↑',sortDesc:'Price ↓',
    res:'results',dinar:'IQD',sizes:'Sizes',
    discount:'50% OFF',lastSize:'⚠️ Last size',share:'Share',
    saved:'Saved',copyId:'ID copied',
    cartT:'Cart',wishT:'Wishlist',contactT:'Contact Us',
    checkout:'Checkout',clearCart:'Clear Cart',shareCart:'Share Cart',
    cartEmpty:'Cart is empty 🛒',
    sub:'Subtotal',ship:'Shipping',tot:'Total',subDisc:'After 50% OFF',
    ckTitle:'Customer Info',namePh:'Full name',phonePh:'Phone number',addrPh:'Address...',
    wa:'WhatsApp',tg:'Telegram',orderNote:'You must send the message to confirm the order',
    cancel:'Cancel',back:'Back →',tapSizeToAdd:'Tap a size to add',addCart:'Add to Cart',navInstall:'Install',swipeHint:'Swipe left to remove item',appInstalled:'App installed',alreadyInstalled:'App already installed!',androidInstallDesc:'Tap the button to install the store on your home screen.',installNow:'Install Now',iosStep1:'Open the store in Safari',iosStep2:'Tap the Share button ↑ at the bottom',iosStep3:'Choose Add to Home Screen',iosStep4:'Tap Add — done!',desktopStep1:'Open the browser menu ⋮',desktopStep2:'Find Install App',desktopStep3:'Click Install — done!',szTitle:'Choose the size',
    loading:'Loading...',noRes:'No results 😕',
    errMsg:'Failed to load products',retry:'Try Again',
    cartAdded:'Added to cart 🛒',already:'Item already in cart',
    delQ:'Remove this item from the cart?',clrQ:'Clear the entire cart?',
    yes:'Yes',no:'Cancel',
    sentQ:'Was the order message sent successfully?',sentY:'Yes, sent',sentN:'Not sent',
    clrAfQ:'Empty the cart now?',clrAY:'Yes, empty it',clrAN:'No, keep it',
    footer:'© 2025 Jood ALabbas Store — All rights reserved',
    navHome:'Home',navSearch:'Search',navCart:'Cart',navWish:'Wishlist',navContact:'Contact',
    fpTitle:'📏 Size Guide',fpClose:'Close',
    pwaTxt:'📲 Install the app on your phone!',pwaInst:'Install',pwaSkip:'Later',
    offline:'Cached data — check your connection',ptrTxt:'Pull to refresh',
    s55:'0-2 months',s60:'2-4 months',s65:'4-6 months',s70:'6-8 months',s75:'8-10 months',
    s80:'1 year',s90:'2 years',s100:'3 years',s110:'4 years',s120:'4-5 years',
    s130:'6-7 years',s140:'8-9 years',s150:'10-11 years',s160:'12-13 years',s170:'14-15 years',
    tut:[
'📏 Size Guide\nTap the red ruler button 📐 at the bottom-left of the screen to open the size chart and find the right size for your child\'s age.',
'🔍 Find a Product\nType the product ID or size number in the search box. You can also tap any product\'s # number directly to copy it.',
'⚙️ Filters\nTap the "Filters" button to filter products by season (Summer / Winter / Spring), type (Outdoor / Home), or sort by price. The number on the button shows active filters.',
'🛒 Add to Cart\nEach product shows its sizes as colored buttons directly. Tap the size you want to add it to the cart instantly with one tap — no extra steps!',
'🛍️ Cart & Checkout\nTap the cart button 🛒 in the bottom bar to review your order.\n• Swipe any item left to remove it\n• Tap "Checkout", enter your name, number, and address, then tap Confirm Order.',
'📞 Contact\nTo get in touch and view our social networks, tap "Contact" in the bottom bar.',
'🌙 Settings\n• Change the language (عربي / English / کوردی) from the language buttons in the header\n• Enable dark mode 🌙 from the button next to the language\n• Pull the page down to refresh products\n• You can install the store as an app on your phone!'
    ],
    copyBtn:'Copy order text',savingOrder:'Saving your order...',savingSub:'Please wait, do not close the page',confirmOrder:'Confirm Order',orderNoteNew:'Your order will be registered and we will contact you soon',orderSuccess:'Your order registered successfully! We will contact you soon 🎉',orderSuccessOk:'OK',orderFail:'Failed to register order, please try again',tryAgain:'Try Again'
  },
  ku:{
    dir:'rtl',
    hTitle:'فرۆشگای جود العباس',hSub:'Jood ALabbas Store',
    welcome:'بەخێربێن بۆ فرۆشگای جود العباس! بازاڕکردنێکی خۆش 🌟',
    promo:'داشکاندنی ٪٥٠ — کۆتایی پێدەهێنێت لە:',
    search:'بگەڕێ بە ID یان قەبارە...',rst:'سڕینەوە',
    fltBtn:'فلتەرەکان',applyFlt:'پیشاندانی ئەنجامەکان',resetFlt:'سڕینەوەی فلتەرەکان',
    seaLbl:'وەرزە',typLbl:'جۆر',sortLbl:'ڕیزکردن بەپێی',
    all:'هەموو',sum:'☀️ هاوینە',win:'❄️ زستانە',spr:'🌸 بەھارە',out:'👗 دەرەوە',hom:'🏠 ماڵەوە',
    sortDef:'بنەڕەتی',sortAsc:'نرخ ↑',sortDesc:'نرخ ↓',
    res:'ئەنجام',dinar:'دینار',sizes:'قەبارەکان',
    discount:'داشکاندنی ٪٥٠',lastSize:'⚠️ دوا قەبارە',share:'هاوبەشکردن',
    saved:'پاشەکەوتت کرد',copyId:'ژمارە کۆپیکرا',
    cartT:'سەبەتە',wishT:'دڵخوازەکان',contactT:'پەیوەندیمان پێوە بکە',
    checkout:'تەواوکردنی کڕین',clearCart:'بەتاڵکردنی سەبەتە',shareCart:'هاوبەشی سەبەتە',
    cartEmpty:'سەبەتە بەتاڵە 🛒',
    sub:'کۆی گشتی سەرەتایی',ship:'کرێی گواستنەوە',tot:'کۆی گشتی کۆتایی',subDisc:'دوای داشکاندنی ٪٥٠',
    ckTitle:'زانیاری کڕیار',namePh:'ناوی تەواو',phonePh:'ژمارەی مۆبایل',addrPh:'ناونیشان...',
    wa:'واتساپ',tg:'تلیگرام',orderNote:'دەبێت نامەکە بنێریت بۆ پشتڕاستکردنەوەی داواکاری',
    cancel:'هەڵوەشاندنەوە',back:'← گەڕانەوە',tapSizeToAdd:'کرتە لە قەبارە بکە بۆ زیادکردن',addCart:'زیادکردن بۆ سەبەتە',navInstall:'دامەزراندن',swipeHint:'بۆ لابردنی کاڵا بەرەو ڕاست بیکێشە',appInstalled:'ئەپەکە دامەزرا',alreadyInstalled:'ئەپەکە پێشتر دامەزراوە!',androidInstallDesc:'کرتە لە دوگمەکە بکە بۆ دامەزراندنی فرۆشگا لەسەر شاشەی سەرەکیت.',installNow:'ئێستا دامەزرێنە',iosStep1:'فرۆشگا لە Safari بکەرەوە',iosStep2:'کرتە لە دوگمەی هاوبەشکردن ↑ لە خوارەوە بکە',iosStep3:'زیادکردن بۆ شاشەی سەرەکی هەڵبژێرە',iosStep4:'کرتە لە زیادکردن بکە — تەواو!',desktopStep1:'مێنیوی وێبگەڕ بکەرەوە ⋮',desktopStep2:'بگەڕێ بۆ دامەزراندنی ئەپ',desktopStep3:'کرتە لە دامەزراندن بکە — تەواو!',szTitle:'قەبارەی پێویست هەڵبژێرە',
    loading:'بارکردن...',noRes:'هیچ ئەنجامێک نییە 😕',
    errMsg:'بارکردنی کاڵاکان سەرنەکەوت',retry:'دووبارە هەوڵبدەرەوە',
    cartAdded:'زیادکرا بۆ سەبەتە 🛒',already:'کاڵا لە سەبەتەدا هەیە',
    delQ:'دەتەوێت ئەم کاڵایە لە سەبەتە بسڕیتەوە؟',clrQ:'دەتەوێت سەبەتە بەتەواوی بەتاڵ بکەیت؟',
    yes:'بەڵێ',no:'هەڵوەشاندنەوە',
    sentQ:'ئایا نامەی داواکاری بە سەرکەوتوویی نێردرا؟',sentY:'بەڵێ، نێردرا',sentN:'نەنێردرا',
    clrAfQ:'دەتەوێت ئێستا سەبەتە بەتاڵ بکەیت؟',clrAY:'بەڵێ، بەتاڵی بکە',clrAN:'نەخێر، بیهێڵەرەوە',
    footer:'© ٢٠٢٥ فرۆشگای جود العباس — هەموو مافەکان پارێزراون',
    navHome:'سەرەکی',navSearch:'گەڕان',navCart:'سەبەتەم',navWish:'دڵخواز',navContact:'پەیوەندی',
    fpTitle:'📏 ڕێنمایی قەبارە',fpClose:'داخستن',
    pwaTxt:'📲 ئەپەکە لەسەر مۆبایلەکەت دابمەزرێنە!',pwaInst:'دامەزراندن',pwaSkip:'دواتر',
    offline:'داتای پاشەکەوتکراو — پەیوەندی بپشکنە',ptrTxt:'بۆ نوێکردنەوە بیکێشە',
    s55:'٠-٢ مانگ',s60:'٢-٤ مانگ',s65:'٤-٦ مانگ',s70:'٦-٨ مانگ',s75:'٨-١٠ مانگ',
    s80:'١ ساڵ',s90:'٢ ساڵ',s100:'٣ ساڵ',s110:'٤ ساڵ',s120:'٤-٥ ساڵ',
    s130:'٦-٧ ساڵ',s140:'٨-٩ ساڵ',s150:'١٠-١١ ساڵ',s160:'١٢-١٣ ساڵ',s170:'١٤-١٥ ساڵ',
    tut:[
'📏 ڕێنمایی قەبارە\nکرتە لە دوگمەی ڕەشبەڵەکی سوور 📐 لە خوارەوەی ڕاستی شاشە بکە بۆ کردنەوەی خشتەی قەبارەکان و زانینی قەبارەی دروست بۆ تەمەنی منداڵەکەت.',
'🔍 گەڕان بۆ کاڵا\nژمارەی کاڵا (ID) یان ژمارەی قەبارە لە خانەی گەڕاندا بنووسە. هەروەها دەتوانیت ڕاستەوخۆ کرتە لە ژمارەی # هەر کاڵایەک بکەیت بۆ کۆپیکردنی.',
'⚙️ فلتەرەکان\nکرتە لە دوگمەی "فلتەرەکان" بکە بۆ فلتەرکردنی کاڵاکان بەپێی وەرز (هاوین / زستان / بەھار) یان جۆر (دەرەوە / ماڵەوە) یان ڕیزکردنیان بەپێی نرخ. ژمارەکە لەسەر دوگمەکە ژمارەی فلتەرە چالاکەکان پیشان دەدات.',
'🛒 زیادکردنی کاڵا بۆ سەبەتە\nهەر کاڵایەک قەبارەکانی وەک دوگمەی ڕەنگاوڕەنگ ڕاستەوخۆ پیشان دەدرێت. کرتە لە قەبارەی پێویست بکە بۆ زیادکردنی خێرا بۆ سەبەتە بە یەک کرتە — بەبێ هەنگاوی زیادە!',
'🛍️ سەبەتە و پارەدان\nکرتە لە دوگمەی سەبەتە 🛒 لە شریتی خوارەوە بکە بۆ پێداچوونەوەی داواکارییەکەت.\n• هەر کاڵایەک بەرەو ڕاست بیکێشە بۆ سڕینەوەی\n• کرتە لە "تەواوکردنی کڕین" بکە، ناو و ژمارە و ناونیشانت بنووسە، دواتر کرتە لە پشتڕاستکردنەوەی داواکاری بکە.',
'📞 پەیوەندی\nبۆ پەیوەندیکردن و بینینی تۆڕە کۆمەڵایەتییەکان کرتە لە "پەیوەندی" لە شریتی خوارەوەی شاشە بکە.',
'🌙 ڕێکخستنەکان\n• زمان بگۆڕە (عربي / English / کوردی) لە دوگمەکانی زمان لە سەرەوە\n• دۆخی تاریک چالاک بکە 🌙 لە دوگمەکە تەنیشت زمان\n• پەڕەکە بەرەو خوارەوە بکێشە بۆ نوێکردنەوەی کاڵاکان\n• دەتوانیت فرۆشگا وەک ئەپ لەسەر مۆبایلەکەت دابمەزرێنیت!'
    ],
    copyBtn:'کۆپیکردنی نامەی داواکاری',savingOrder:'داواکارییەکەت تۆمار دەکرێت...',savingSub:'تکایە چاوەڕوانبە، پەڕەکە دامەخە',confirmOrder:'پشتڕاستکردنەوەی داواکاری',orderNoteNew:'داواکارییەکەت تۆمار دەکرێت و بەم زووانە پەیوەندیت پێوە دەکەین',orderSuccess:'داواکارییەکەت بە سەرکەوتوویی تۆمارکرا! بەم زووانە پەیوەندیت پێوە دەکەین 🎉',orderSuccessOk:'باشە',orderFail:'تۆمارکردنی داواکاری سەرنەکەوت، دووبارە هەوڵبدەرەوە',tryAgain:'دووبارە هەوڵبدەرەوە'
  }
};
